### ISSUE TITLE
Umbrella Issues

### ISSUE THREAD

**Issue by minheq** [WeTrustPlatform/paramount#229]
- [ ] Tabs allow overriding presses
- [ ] Add animated Tabs Panel
- [x] Positioner between navigating screens should reload
- [ ] remove variables from styles
- [ ] allow styles on theme for all components
